export const aiClientDeliveryKitCaseStudy = {
  role: "AI Solutions Engineer",
  projectType: "AI Delivery Operations Toolkit",
  stack: ["Python", "YAML", "GitHub Actions", "Claude", "ChatGPT"],
  attributes: ["3 agent roles", "Dry-run default", "CI validated", "Sample data only"],
  flowSummary: [
    "Account research notes",
    "Executive-ready brief",
    "Quality review report",
    "Weekly GitHub digest",
    "Client handoff checklist",
  ],
  problemItems: [
    "Prompts lose context, versions, and ownership.",
    "Facts, assumptions, and missing inputs blur together.",
    "Client-specific data leaks into reusable assets.",
    "Automation is connected before it can be inspected safely.",
    "Outputs are shared without a consistent quality gate.",
    "Handoff depends on the original builder staying involved.",
  ],
  deliverySteps: [
    ["01", "Configure client context"],
    ["02", "Select approved inputs"],
    ["03", "Run versioned prompt"],
    ["04", "Generate deliverable"],
    ["05", "Validate prompt library"],
    ["06", "Quality review"],
    ["07", "Dry-run automation"],
    ["08", "Approve + hand off"],
  ],
  platforms: [
    ["Claude Code", "Project instructions"],
    ["ChatGPT", "Connector-ready workflow"],
    ["GitHub MCP", "Repository context"],
    ["Python", "Validation + digest"],
    ["GitHub Actions", "CI + schedule"],
  ],
  architecture: [
    {
      title: "INPUT + POLICY",
      items: [["client-config.yaml", "Scope, audience, controls"], ["approved notes", "Evidence and account context"], ["environment", "Local-only secrets"]],
    },
    {
      title: "DELIVERY ENGINE",
      items: [["prompts/", "Research · brief · QA"], ["scripts/", "Validate · bootstrap · digest"], ["platform-config/", "Claude · ChatGPT · MCP"]],
    },
    {
      title: "CONTROL LAYER",
      items: [["pytest", "Network-free unit tests"], ["GitHub Actions", "Validation + weekly schedule"], ["quality review", "Pass/fail + remediation"]],
    },
    {
      title: "OUTPUT + HANDOFF",
      items: [["examples/", "Curated safe samples"], ["outputs/", "Ignored generated work"], ["docs/", "Setup · security · handoff"]],
    },
  ],
  decisions: [
    ["Configuration before customization", "Client scope, audience, deliverables, safety posture, and dry-run behavior live in one explicit YAML contract instead of being scattered across prompts."],
    ["Versioned prompt operations", "Each prompt declares an ID, version, status, inputs, outputs, and review criteria so prompt changes can be reviewed like code."],
    ["Dry-run as the default", "GitHub digest generation stays offline and uses sample data unless live mode is explicitly requested with a local token."],
    ["Human approval as a boundary", "Agents prepare research, briefs, and QA notes; the delivery owner decides what is approved for external sharing."],
    ["Network-free testability", "Validation and unit tests run without live services, making CI predictable and safe for a public reference project."],
    ["Documentation is part of delivery", "Setup, data flow, security, restricted environments, release, and handoff guidance ship with the automation."],
  ],
  safetyControls: [
    ["Sample data only", "Committed examples contain fictional B2B SaaS context, never real customer data."],
    ["Secrets stay local", "Tokens come from environment variables or an approved secret manager."],
    ["Least privilege", "Live GitHub reads use only the metadata scopes required for the digest."],
    ["External review gate", "Generated deliverables are reviewed before client sharing."],
    ["Explicit live mode", "A token alone cannot activate live access; the command also requires --live."],
    ["Restricted fallback", "Offline and constrained-environment operating options are documented."],
  ],
  reviewFlow: ["Approved inputs", "Draft output", "Quality review", "Pass / remediate", "Delivery owner approval", "External handoff"],
  safetyTags: ["PII redact", "Facts ≠ assumptions", "No unsupported claims", "Outputs ignored", "Read-only token", "Manual approval"],
  outputs: [
    "Prompt library",
    "Agent boundaries",
    "Client configuration",
    "Python automation",
    "CI workflows",
    "Sample deliverables",
    "Operating documentation",
    "Release discipline",
    "Safe adaptation path",
  ],
  tests: [
    ["Valid prompt metadata", "Library validates successfully"],
    ["Missing YAML frontmatter", "Validation fails before delivery"],
    ["Duplicate prompt IDs", "Conflicting definitions are rejected"],
    ["Category mismatch", "Folder and metadata inconsistency is flagged"],
    ["Bootstrap dry-run", "No output directories are created"],
    ["Digest with sample config", "Expected core sections are generated"],
    ["String include flags", "Configuration is parsed predictably"],
    ["Authenticated live request", "Read request contains required headers"],
    ["Digest window filter", "Old issues, PRs and releases are excluded"],
    ["Rate-limit response", "Clear error without token exposure"],
    ["Live mode without token", "Execution stops with actionable guidance"],
    ["CI workflow", "Prompt validation and pytest run cleanly"],
  ],
  capabilities: ["Prompt ops", "Client configuration", "GitHub automation", "Quality gates", "Security by default", "CI / testing", "Handoff design"],
} as const;
