import {
  mainIntakeAndParser,
  mainOrchestration,
  mainOverview,
  mainValidationAndDeduplication,
  subFinishMaterialSheet as materialsImage,
  subProjectWorkspace as workspaceImage,
  subQuickBooksRecord as quickBooksImage,
  sysAuditService as auditImage,
  sysErrorHandler as errorHandlerImage,
} from "../assets/images/project-onboarding-automation";

export const onboardingCaseStudy = {
  role: "Automation Engineer",
  projectType: "Business Process Automation and Systems Integration",
  heroIntro: "An end-to-end business automation that transforms a signed construction contract into a fully initialized project across operational, financial, and client communication systems.",
  attributes: ["6 connected systems", "Idempotent", "Audit logged", "Centralized error routing"],
  flowSummary: ["Signed contract", "Validate + deduplicate", "Create project workspace", "Financial setup", "Client communication", "Audit + completion"],
  problemItems: [
    "Creating a project folder and organizing the signed contract.",
    "Creating customer, project, estimate, and invoice records in QuickBooks.",
    "Preparing a finish material sheet.",
    "Sending the client welcome email.",
    "Updating the project management dashboard.",
    "Tracking what had already been completed.",
  ],
  workflowSteps: [
    "Download and parse the PDF contract.", "Normalize the client, project, milestone, and material data.",
    "Validate all required fields before creating external resources.", "Check the Slack event ID to prevent duplicate processing.",
    "Open an audit run.", "Create the project folder structure in Google Drive.", "Upload the signed contract.",
    "Create the customer, project, and estimate in QuickBooks.", "Generate the project finish material sheet.",
    "Send the client welcome email.", "Add the project to the internal PM dashboard.",
    "Create and send the deposit invoice.", "Close the audit run with the final workflow status.",
  ],
  integrations: [
    ["Slack", "Workflow trigger and contract intake"], ["n8n", "Workflow orchestration"],
    ["Google Drive", "Project workspace and document storage"], ["QuickBooks Online", "Customer, project, estimate, and invoice records"],
    ["Google Sheets", "Material sheet, PM dashboard, and audit records"], ["Gmail", "Client welcome email"],
  ],
  architectureComponents: [
    { title: "MAIN — New Project Onboarding", copy: "Owns Slack intake, PDF extraction, normalization, validation, deduplication, sequencing, inline communication and financial steps, and the final response." },
    { title: "SUB — Create Project Workspace", copy: "Creates the Google Drive folder structure and uploads the signed contract. Returns folder_id and upload_id." },
    { title: "SUB — Create QB Record", copy: "Creates the QuickBooks customer, project, and estimate. Returns customer_id, project_id, estimate_id, and estimate_number." },
    { title: "SUB — Create Finish Material Sheet", copy: "Creates the project material sheet, writes extracted rows, and returns sheet_id and sheet_url." },
    { title: "SYS — Audit Service", copy: "Provides reusable CREATE_RUN, APPEND_EVENT, and UPDATE_RUN operations." },
    { title: "SYS — Error Handler", copy: "Normalizes and classifies errors, updates audit state, and sends operator-facing Slack notifications." },
  ],
  decisions: [
    ["Deterministic parsing instead of unnecessary AI", "The workflow processes a known proposal template, so deterministic extraction and validation provide more predictable behavior than an LLM-based parser."],
    ["Orchestrator plus focused sub-workflows", "The main workflow coordinates the process while separate workflows own cohesive integration responsibilities."],
    ["Fail-fast validation before side effects", "Required fields are verified before Drive folders, QuickBooks records, emails, sheets, or invoices are created."],
    ["Idempotency through the source event ID", "The Slack event identifier is the deduplication key, so replaying the same event does not repeat downstream side effects."],
    ["Accumulated workflow state", "Every successful step returns the existing state plus its own result namespace for dependent steps, audit records, and recovery context."],
    ["Manual recovery instead of unsafe rollback", "Independent external platforms do not share a transaction boundary, so partial completion is recorded for informed recovery instead of unsafe automatic deletion."],
  ],
  reliability: [
    ["Fail-fast validation", "Required contract fields are checked before any external resources are created. Invalid client, project, or milestone data stops the workflow before partial records can be produced."],
    ["Duplicate protection", "The original Slack event ID acts as an idempotency key, so replaying an event does not recreate Drive, QuickBooks, email, sheet, or invoice resources."],
    ["Centralized audit logging", "Run- and step-level events show when execution started, which steps completed, where it failed, and which external resources already exist."],
    ["Structured error handling", "Unhandled failures go to one shared workflow and are classified as validation, authentication, rate-limit, transient API, or data-contract errors."],
    ["Recovery-oriented notifications", "Slack alerts include the execution, failed step, error code, retryability, created resources, and the last successful operation."],
    ["Controlled partial failures", "External systems share no transaction boundary, so the MVP records partial completion and routes it for manual review instead of attempting unsafe automatic rollback."],
  ],
  errorTypes: ["VALIDATION_FAILED", "EXTRACTION_FAILED", "DUPLICATE_CONFLICT", "API_AUTH_FAILED", "API_RATE_LIMITED", "API_TRANSIENT", "API_PERMANENT", "DATA_CONTRACT_FAILED", "AUDIT_FAILED", "UNKNOWN"],
  tests: [
    ["Valid kitchen remodel contract", "Complete project setup and successful audit run"],
    ["Valid bathroom remodel contract", "Complete setup without relying on one hardcoded project type"],
    ["Valid sunroom contract", "Complete project setup with correct totals and deposit"],
    ["Invalid PDF binary", "Stop before audit run and notify Slack"],
    ["Unsupported contract layout", "Report extraction failure before creating resources"],
    ["Missing client email", "Report validation failure before external side effects"],
    ["Missing project type", "Report validation failure before external side effects"],
    ["Missing milestones", "Stop before financial records are created"],
    ["Replayed Slack event ID", "Skip repeated side effects"],
    ["Broken downstream credential", "Record partial failure and notify the operator"],
    ["Audit logging failure", "Still attempt Slack notification without an error loop"],
  ],
  outputs: ["Google Drive project folder created", "Signed contract uploaded", "QuickBooks customer created", "QuickBooks project created", "QuickBooks estimate created with milestone line items", "Finish material sheet created and populated", "Welcome email sent", "PM dashboard row added", "Deposit invoice created and sent", "Audit run closed with SUCCESS"],
  included: ["Deterministic parsing for a known proposal template", "Validation before downstream side effects", "Idempotent processing through the source event ID", "Drive, QuickBooks, Sheets, Gmail, and Slack integrations", "Run-level and step-level audit logging", "Centralized operator notifications", "Happy-path and failure-path fixtures", "Sandbox-ready workflow exports and synthetic examples"],
  excluded: ["AI interpretation of arbitrary contracts", "Automatic business decisions", "Automatic rollback across independent systems", "Fully automated resume-from-failure workflows", "Production deployment hardening", "A claim of live client production usage"],
  capabilities: ["Workflow architecture", "Separation of responsibilities", "API and platform integrations", "State management", "Idempotency", "Validation before side effects", "Audit logging and observability", "Failure classification", "Human-in-the-loop recovery", "Failure-path testing"],
  visuals: {
    mainOverview,
    mainIntakeAndParser,
    mainValidationAndDeduplication,
    mainOrchestration,
    workspaceImage,
    quickBooksImage,
    materialsImage,
    auditImage,
    errorHandlerImage,
  },
} as const;
